revert numpy version
to address Docker build pip install failure:
ImportError: Numba needs NumPy 1.21 or less
(ultimately from scanpy, which requires numba)